# fly.toml app configuration file generated for abacus-electronics-server-side on 2023-10-22T00:11:39+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "abacus-electronics-server-side"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
